feat(Enjoy2Live): hide existing open roles for later use
dev-launchers/strapi pull request #139
Opened 2021-09-03 13:30 UTC by Enjoy2Live

2021-09-05 14:14 UTC, chungthuang approved these changes

2021-09-06 04:34 UTC, alearm246 commented on api/idea-card/documentation/1.0.0/idea-card.json
> +                "isHidden": {
So is this field supposed to hide the open roles? If so, wouldn't it be better to name it isOpenRolesHidden for clarity?

2021-09-06 04:35 UTC, alearm246 requested changes
So is this field supposed to hide the open roles? If so, wouldn't it be better to name it isOpenRolesHidden for clarity?

2021-09-17 01:04 UTC, Enjoy2Live commented
> So is this field supposed to hide the open roles? If so, wouldn't it be better to name it isOpenRolesHidden for clarity?

These are bound to every single open role in the array, so it hides individual roles. 

![image](https://user-images.githubusercontent.com/27841994/133707477-fb539dae-7987-41a2-8aa1-19ac82a07bbc.png)

2021-09-17 01:28 UTC, alearm246 commented
> > So is this field supposed to hide the open roles? If so, wouldn't it be better to name it isOpenRolesHidden for clarity?
> 
> These are bound to every single open role in the array, so it hides individual roles.
> 
> ![image](https://user-images.githubusercontent.com/27841994/133707477-fb539dae-7987-41a2-8aa1-19ac82a07bbc.png)

Oh ok that makes much more sense

2021-09-17 01:28 UTC, alearm246 approved these changes

2021-09-20 05:12 UTC, merged